name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Specify the Node version if needed

      - name: Install dependencies
        run: |
          npm install
          echo 'Dependencies installed'
        working-directory: ./client

      - name: Check npm install log
        run: cat ./client/npm-debug.log || echo 'No debug log found'
        working-directory: ./

      - name: Verify Node modules
        run: ls -al ./client/node_modules
        working-directory: ./client

      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Display build logs
        run: cat ./client/npm-debug.log || echo 'No debug log found'
        working-directory: ./

      - name: List build directory contents
        run: ls -al ./client/dist
        working-directory: ./client

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./client/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
